version: "3.1"

services:

  desafio_db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
